language: python
python:
 - 3.7

before_install:
    - pip install mesa
    - pip install ipynb
    - pip install axelrod
    - pip install ipython==6.2.1
    - pip install jupyter_console==5.2.0
    - pip install statsmodels
    - pip install SALib
    - pip install pycodestyle
    - pip install autopep8
    
notifications:
  email: false
  slack:
   - rooms:
      - asian-pacedyodeling:KUcuh0LZlw6M6dOe96wR2DE0#github_code
      on_success: always
      on_failure: never
      result: "fucking worked"
      message: "Yo wtf dude, you high or smth? You clearly fucked up"
      template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} the great %{result} in %{duration}"
   - rooms:
      - asian-pacedyodeling:KUcuh0LZlw6M6dOe96wR2DE0#github_code
      - asian
      on_success: never
      on_failure: always
      result: "Failed miserably"
      message: "Success, you successfully succeeded, now go get Dobby's coffee"
      template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
      - "%{message}"


script:
    - git remote rm origin
    - git remote add origin https://hildobby:${GITHUB_API_KEY}@github.com/hildobby/Asian-paced_Yodeling.git
    # Run pep8 on all .py files in all subfolders
    # We must ignore E402 module level import not at top of file
    # because of use case sys.path.append('..'); import <module>
    - num_errors_before=`find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} + | wc -l`
    - echo $num_errors_before

    - cd "$TRAVIS_BUILD_DIR"
    - git config --global user.email "h.moulie@gmail.com"
    # From https://help.github.com/articles/setting-your-username-in-git/:
    # "Tip: You don't have to use your real name--any name works. Git 
    # actually associates commits by email address; the username is only 
    # used for identification. If you use your email address associated 
    # with a GitHub account, we'll use your GitHub username, instead of 
    # this name.
    - git config --global user.name "Travis"
    - git checkout $TRAVIS_BRANCH

    - find . -name \*.py -exec autopep8 --max-line-length=120 --recursive --aggressive --aggressive --in-place {} +
    - num_errors_after=`find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402  {} + | wc -l`
    - echo $num_errors_after

    - |
        if (( $num_errors_after < $num_errors_before )); then
            git commit -a -m "PEP-8 Fix"
            git config --global push.default simple # Push only to the current branch.  
            # Make sure to make the output quiet, or else the API token will 
            # leak!  This works because the API key can replace your password.
            git push --set-upstream origin master
            git push --quiet
        fi
    - cd "$TRAVIS_BUILD_DIR"

    # List the remaining errors - these will have to be fixed manually
    - find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
