language: python
python:
 - 3.7

before_install:
    - pip install mesa
    - pip install ipynb
    - pip install axelrod
    - pip install ipython==6.2.1
    - pip install jupyter_console==5.2.0
    - pip install statsmodels
    - pip install SALib
    - pip install pycodestyle
    - pip install autopep8
    
notifications:
  email: false
  slack:
    - rooms:
        - asian-pacedyodeling:KUcuh0LZlw6M6dOe96wR2DE0
      on_success: never
      on_failure: always
      template:
        - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author} the great failed miserably in %{duration}"
        - "Yo wtf dude, you high or smth? You clearly fucked up :eggplant: :: "
        - ":letter_y::letter_o::letter_u:  :letter_m::letter_i::letter_s::letter_e::letter_r::letter_a::letter_b::letter_l::letter_e:  :letter_p::letter_i::letter_e::letter_c::letter_e:  :letter_o::letter_f:  :letter_s::letter_h::letter_i::letter_t::exclamation:"
    - rooms:
        - asian-pacedyodeling:KUcuh0LZlw6M6dOe96wR2DE0
      on_success: always
      on_failure: never
      template:
        - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author} the great fucking worked in %{duration}"
        - "Success, you successfully succeeded! :baby-yoda-soup: :aww_yeah:"
        - ":letter_g::letter_o::letter_o::letter_d:  :letter_j::letter_o::letter_b::grey_exclamation:"

script:
    - git remote rm origin
    - git remote add origin https://hildobby:${GITHUB_API_KEY}@github.com/hildobby/Asian-paced_Yodeling.git
    # Run pep8 on all .py files in all subfolders
    # We must ignore E402 module level import not at top of file
    # because of use case sys.path.append('..'); import <module>
    - num_errors_before=`find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} + | wc -l`
    - echo $num_errors_before

    - cd "$TRAVIS_BUILD_DIR"
    - git config --global user.email "h.moulie@gmail.com"
    # From https://help.github.com/articles/setting-your-username-in-git/:
    # "Tip: You don't have to use your real name--any name works. Git 
    # actually associates commits by email address; the username is only 
    # used for identification. If you use your email address associated 
    # with a GitHub account, we'll use your GitHub username, instead of 
    # this name.
    - git config --global user.name "Travis"
    - git checkout $TRAVIS_BRANCH

    - find . -name \*.py -exec autopep8 --max-line-length=120 --recursive --aggressive --aggressive --in-place {} +
    - num_errors_after=`find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402  {} + | wc -l`
    - echo $num_errors_after

    - |
        if (( $num_errors_after < $num_errors_before )); then
            git commit -a -m "PEP-8 Fix"
            git config --global push.default simple # Push only to the current branch.  
            # Make sure to make the output quiet, or else the API token will 
            # leak!  This works because the API key can replace your password.
            git push --set-upstream origin master
            git push --quiet
        fi
    - cd "$TRAVIS_BUILD_DIR"

    # List the remaining errors - these will have to be fixed manually
    - find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
